services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cishackit
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8080:80
    networks:
      - cishackit
    restart: unless-stopped
    depends_on:
      - postgres

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - cishackit
    restart: unless-stopped


volumes:
  postgres:

networks:
  cishackit:
    driver: bridge
